version: '3.9'

services:
  ros_vision_pipeline:
    container_name: ros_vision_pipeline
    # docker-compose build --build-arg 'TARGET=gpu'
    image: reconcycle:ros_vision_pipeline
    build:
      context: ./build
      args:
        TARGET: gpu
        UID: 1000 # bash: id -u
        GID: 1000 # bash: id -g
    environment:
      - ROS_MASTER_URI=http://10.20.0.1:11311
      - ROS_IP=10.20.0.2 # $ hostname -I
      - DISPLAY=$DISPLAY
      #
      # If the computer has CUDA support:
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=all
      # colours in log
      - DEBUG_COLORS=true
      - TERM=xterm-256color
      - COLORTERM=truecolor
    tty: true # keep container running
    volumes:
      - $HOME/reconcycle/vision_pipeline:/home/docker/vision_pipeline
      - ./catkin_ws:/home/docker/catkin_ws
      - "/tmp/.X11-unix:/tmp/.X11-unix" # for using local xserver
    command: python ros_pipeline.py
    privileged: true # fixes nvidia sometimes breaking # https://github.com/NVIDIA/nvidia-docker/issues/1671
    network_mode: "host"
    restart: "unless-stopped"
